services:
    ghost:
        image: ghost:latest
        restart: always
        ports:
            - "2368:2368"
        depends_on:
            - db
        environment:
            url: https://blog.meanii.dev
            database__client: mysql
            database__connection__host: db
            database__connection__user: ghost
            database__connection__password: ghostdbpass
            database__connection__database: ghostdb
        volumes:
            - "./ghost/content:/var/lib/ghost/content"

    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
            MYSQL_USER: ghost
            MYSQL_PASSWORD: ghostdbpass
            MYSQL_DATABASE: ghostdb
        volumes:
            - "./ghost/mysql:/var/lib/mysql"
